# TCL File Generated by Component Editor 18.1
# Fri Nov 23 22:50:03 CST 2018
# DO NOT MODIFY


# 
# AI_Core "AI_Core" v1.0
#  2018.11.23.22:50:03
# Communication between AI and hardware
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AI_Core
# 
set_module_property DESCRIPTION "Communication between AI and hardware"
set_module_property NAME AI_Core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ECE 385 Final Project Custom IP"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME AI_Core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AI_interface.sv SYSTEM_VERILOG PATH AI_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AI_interface.sv SYSTEM_VERILOG PATH AI_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point AI_Slave
# 
add_interface AI_Slave avalon end
set_interface_property AI_Slave addressUnits WORDS
set_interface_property AI_Slave associatedClock CLK
set_interface_property AI_Slave associatedReset RESET
set_interface_property AI_Slave bitsPerSymbol 8
set_interface_property AI_Slave burstOnBurstBoundariesOnly false
set_interface_property AI_Slave burstcountUnits WORDS
set_interface_property AI_Slave explicitAddressSpan 0
set_interface_property AI_Slave holdTime 0
set_interface_property AI_Slave linewrapBursts false
set_interface_property AI_Slave maximumPendingReadTransactions 0
set_interface_property AI_Slave maximumPendingWriteTransactions 0
set_interface_property AI_Slave readLatency 0
set_interface_property AI_Slave readWaitStates 0
set_interface_property AI_Slave readWaitTime 0
set_interface_property AI_Slave setupTime 0
set_interface_property AI_Slave timingUnits Cycles
set_interface_property AI_Slave writeWaitTime 0
set_interface_property AI_Slave ENABLED true
set_interface_property AI_Slave EXPORT_OF ""
set_interface_property AI_Slave PORT_NAME_MAP ""
set_interface_property AI_Slave CMSIS_SVD_VARIABLES ""
set_interface_property AI_Slave SVD_ADDRESS_GROUP ""

add_interface_port AI_Slave AI_ADDR address Input 4
add_interface_port AI_Slave AI_BYTE_EN byteenable Input 2
add_interface_port AI_Slave AI_READDATA readdata Output 16
add_interface_port AI_Slave AI_WRITEDATA writedata Input 16
add_interface_port AI_Slave AI_WRITE write Input 1
add_interface_port AI_Slave AI_CS chipselect Input 1
add_interface_port AI_Slave AI_READ read Input 1
set_interface_assignment AI_Slave embeddedsw.configuration.isFlash 0
set_interface_assignment AI_Slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AI_Slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AI_Slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point EXPORT_DATA
# 
add_interface EXPORT_DATA conduit end
set_interface_property EXPORT_DATA associatedClock CLK
set_interface_property EXPORT_DATA associatedReset ""
set_interface_property EXPORT_DATA ENABLED true
set_interface_property EXPORT_DATA EXPORT_OF ""
set_interface_property EXPORT_DATA PORT_NAME_MAP ""
set_interface_property EXPORT_DATA CMSIS_SVD_VARIABLES ""
set_interface_property EXPORT_DATA SVD_ADDRESS_GROUP ""

add_interface_port EXPORT_DATA EXPORT_DATA new_signal Output 16


# 
# connection point Enemy_Loc
# 
add_interface Enemy_Loc conduit end
set_interface_property Enemy_Loc associatedClock CLK
set_interface_property Enemy_Loc associatedReset ""
set_interface_property Enemy_Loc ENABLED true
set_interface_property Enemy_Loc EXPORT_OF ""
set_interface_property Enemy_Loc PORT_NAME_MAP ""
set_interface_property Enemy_Loc CMSIS_SVD_VARIABLES ""
set_interface_property Enemy_Loc SVD_ADDRESS_GROUP ""

add_interface_port Enemy_Loc Enemy_Loc new_signal Input 16


# 
# connection point Player_Loc
# 
add_interface Player_Loc conduit end
set_interface_property Player_Loc associatedClock CLK
set_interface_property Player_Loc associatedReset ""
set_interface_property Player_Loc ENABLED true
set_interface_property Player_Loc EXPORT_OF ""
set_interface_property Player_Loc PORT_NAME_MAP ""
set_interface_property Player_Loc CMSIS_SVD_VARIABLES ""
set_interface_property Player_Loc SVD_ADDRESS_GROUP ""

add_interface_port Player_Loc Player_Loc new_signal Input 16


# 
# connection point Enemy_Data
# 
add_interface Enemy_Data conduit end
set_interface_property Enemy_Data associatedClock CLK
set_interface_property Enemy_Data associatedReset RESET
set_interface_property Enemy_Data ENABLED true
set_interface_property Enemy_Data EXPORT_OF ""
set_interface_property Enemy_Data PORT_NAME_MAP ""
set_interface_property Enemy_Data CMSIS_SVD_VARIABLES ""
set_interface_property Enemy_Data SVD_ADDRESS_GROUP ""

add_interface_port Enemy_Data Enemy_Data new_signal Output 16

